[Interface]
PrivateKey = 6KbiDyJUYZRwA9TBm9CdGXy5rRYkPXXDUfXFfb2MeWY=
Address = 10.0.0.2/24
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = Vbj0jHUxGNmR0NvhBXlOdDgfV4NYM9UZJQQg9hFGbkY=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = demo.wireguard.com:51820
PersistentKeepalive = 25
